### ISSUE TITLE
Why rust instead of go?

### ISSUE THREAD

**Issue by ghost** [rnbguy/rope#5]
I want to [make a p2p program](https://lemmy.ml/post/622702) and I'm wondering which one to choose. What is the reason why you chose to move the program to rust?

**Comment by rnbguy** [comment]
Sorry that I missed your question. The reason I moved to Rust is rather personal. I started coding a lot in Rust.

I think Go still has the best support for P2P layer. If you look at the [libp2p implementations](https://libp2p.io/implementations), you will notice Go still has better support than Rust.
